PUT http://localhost/api-qr-tandem/v1/change-password.php
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjE3MjU4NTgsImV4cCI6MTc1MjgyOTg1OCwidXNlcklkIjoyNSwiZW1haWwiOiJyb2JlcnRvQGdtYWlsLmNvbSIsInJvbGUiOiJndWVzdCJ9.kQhhxijE2iET2b4RaygVG-kpLEBEWAbo4xEKFwJ59Ac"

{
    "email": "roberto@gmail.com",
    "password": "asdf" 
}