PUT http://localhost/api-qr-tandem/v1/change-password.php
Content-Type: "application/json"
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjE4MDYyMzMsImV4cCI6MTc1MjkxMDIzMywidXNlcklkIjozLCJlbWFpbCI6Imludml0YWRvQGdtYWlsLmNvbSIsInJvbGUiOiJndWVzdCJ9.gXac-0hMn2kd2MRrYb7OdK_HXJ1gUjj8OmWoYieYYU8

{
    "email": "invitado@gmail.com",
    "password": "12345" 
}