POST  http://localhost/api-qr-tandem/v1/email-soporte.php
Content-Type: "application/json"

{
    "nombre": "Helena",
    "email": "helena@gmail.com",
    "asunto": "Urgente",
    "mensaje": "Necesito ayuda" 
}