GET http://localhost/api-qr-tandem/v1/list-users.php 
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjAwNzc4NDEsImV4cCI6MTc1MTE4MTg0MSwidXNlcklkIjoxLCJlbWFpbCI6ImdlcmVudGVAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIn0.CEfjjDBbONpxSJyf0B9nk_EDcvrDrFe7oeAKIL5Wz4I
Content-Type: "application/json"