GET http://localhost/api-qr-tandem/v1/list-users.php 
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjE4MDQwNzgsImV4cCI6MTc1MjkwODA3OCwidXNlcklkIjoxLCJlbWFpbCI6ImdlcmVudGVAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIn0.mfCLFRzmGZ8s-EoxH6oh27aEsiFlhe-CnvBlt-Aoa_k
Content-Type: "application/json"