PUT http://localhost/api-qr-tandem/v1/update-user.php
Content-Type: application/json
Authorization: Bearer TU_TOKEN

{
    "id": 1,
    "email": "gerente@gmail.com",
    "role": "admin"
}

###
PUT http://localhost/api-qr-tandem/v1/update-user.php
Content-Type: application/json

{
    "id": 2,
    "email": "empleado@gmail.com",
    "role": "employee"
}

###
PUT http://localhost/api-qr-tandem/v1/update-user.php
Content-Type: application/json

{
    "id": 3,
    "nombre": "Invitado",
    "email": "invitado@gmail.com",
    "delegacion": "Mallorca"
}

### Modificar Datos Completos
PUT http://localhost/api-qr-tandem/v1/update-user.php
Content-Type: application/json

{
    "nombre": "Invitado2Prueba",
    "delegacion": "Mallorca",
    "email": "invitado2@example.com"
}

### Modificar si falta un campo
PUT http://localhost/api-qr-tandem/v1/update-user.php
Content-Type: application/json

{
    "nombre": "Invitado2Prueba",
    "delegacion": "Mallorca"
}

### Email correcto y otros campos en blanco
PUT http://localhost/api-qr-tandem/v1/update-user.php
Content-Type: application/json

{
    "nombre": "",
    "delegacion": "",
    "email": "invitado2@gmail.com"
}

### Datos en blanco
PUT http://localhost/api-qr-tandem/v1/update-user.php
Content-Type: application/json

{
    "nombre": "",
    "delegacion": "",
    "email": ""
}